name: Deploy Fuwari to Pages-Repo

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：先拉取代码（必须在所有依赖操作前）
      - name: Checkout ForestBlog-Source
        uses: actions/checkout@v4
        with:
          submodules: true

      # 步骤2：同时设置Node.js和pnpm（官方action，确保顺序正确）
      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v4  # 使用官方action，自动处理安装和路径
        with:
          node-version: 20.x        # 同时指定Node版本
          pnpm-version: 8           # 明确pnpm版本
          run_install: false        # 暂不自动安装依赖

      # 步骤3：验证pnpm是否可用（安装后立即检查）
      - name: Verify pnpm installation
        run: |
          pnpm --version  # 确认pnpm可被识别
          which pnpm      # 显示安装路径

      # 步骤4：安装项目依赖（此时pnpm已确保可用）
      - name: Install dependencies
        run: pnpm install

      # 步骤5：构建项目
      - name: Build Fuwari site
        run: pnpm run build

      # 步骤6：配置SSH密钥
      - name: Setup SSH key for Pages-Repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      # 步骤7：部署到公开仓库
      - name: Deploy to Pages-Repo
        run: |
          cd dist
          git init
          git config --global user.name "DerckHanna"
          git config --global user.email "2261629229@qq.com"
          git remote add origin git@github.com:DerckHanna/Pages-Repo.git
          git checkout -b gh-pages
          git add .
          git commit -m "Auto deploy: $(date +'%Y-%m-%d %H:%M:%S')"
          git push -f origin gh-pages
    