name: Deploy Astro Site to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'

      # 通过 npm 安装 pnpm（最可靠的方式）
      - name: Install pnpm globally
        run: |
          npm install -g pnpm@9.14.4
          echo "PNPM version: $(pnpm --version)"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Astro project
        run: pnpm run build

      # 步骤 6: 部署到公开仓库 - 使用 PAT_TOKEN
      - name: Deploy to Public Repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 关键修改：使用 PAT_TOKEN 而不是 GITHUB_TOKEN
          github_token: ${{ secrets.PAT_TOKEN }}  # 这里必须与你添加的 secret 名称一致
          external_repository: DerckHanna/Pages-Repo
          publish_branch: gh-pages
          publish_dir: ./dist
          force_orphan: true
          keep_files: false

      - name: Echo success message
        run: echo "✅ 部署成功！网站已更新。"