name: Deploy Fuwari to Pages-Repo

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ForestBlog-Source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      # 改进pnpm安装步骤，确保正确添加到PATH
      - name: Install pnpm
        uses: pnpm/action-setup@v4  # 使用最新版本的action
        with:
          version: 8  # 明确指定pnpm版本
          run_install: false  # 暂不安装依赖

      # 验证pnpm是否安装成功并显示版本
      - name: Verify pnpm installation
        run: |
          pnpm --version
          echo "PNPM_HOME=$PNPM_HOME"
          echo "$PNPM_HOME" >> $GITHUB_PATH  # 确保pnpm在PATH中

      - name: Install dependencies
        run: pnpm install

      - name: Build Fuwari site
        run: pnpm run build

      - name: Setup SSH key for Pages-Repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to Pages-Repo
        run: |
          cd dist
          git init
          git config --global user.name "DerckHanna"
          git config --global user.email "2261629229@qq.com"
          git remote add origin git@github.com:DerckHanna/Pages-Repo.git
          git checkout -b gh-pages
          git add .
          git commit -m "Auto deploy from ForestBlog-Source: $(date +'%Y-%m-%d %H:%M:%S')"
          git push -f origin gh-pages
    