name: Deploy Astro Site to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 步骤 1: 检出源代码
      - name: Checkout source code
        uses: actions/checkout@v4

      # 步骤 2: 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
          cache: 'pnpm'

      # 步骤 3: 安装 pnpm - 修正版本号写法
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.14.4  # 移除引号，使用数字格式

      # 步骤 4: 验证 pnpm 安装 - 新增步骤
      - name: Verify pnpm installation
        run: pnpm --version

      # 步骤 5: 安装项目依赖
      - name: Install dependencies
        run: pnpm install --frozen-lockfile  # 使用冻结的lockfile确保一致性

      # 步骤 6: 构建 Astro 项目
      - name: Build Astro project
        run: pnpm run build

      # 步骤 7: 部署到公开仓库
      - name: Deploy to Public Repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          external_repository: DerckHanna/Pages-Repo
          publish_branch: gh-pages  # 使用 gh-pages 分支
          publish_dir: ./dist
          force_orphan: true
          keep_files: false

      # 步骤 8: 输出成功信息
      - name: Echo success message
        run: echo "✅ 部署成功！网站已更新。"