name: Deploy Fuwari to ForestBlog-Source (仓库A)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：拉取仓库A的代码
      - name: Checkout ForestBlog-Source
        uses: actions/checkout@v4
        with:
          submodules: true

      # 步骤2：设置Node.js和pnpm
      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v4
        with:
          node-version: 20.x
          pnpm-version: 8
          run_install: false

      # 步骤3：验证pnpm安装
      - name: Verify pnpm installation
        run: |
          pnpm --version
          which pnpm

      # 步骤4：安装依赖
      - name: Install dependencies
        run: pnpm install

      # 步骤5：构建项目
      - name: Build Fuwari site
        run: pnpm run build

      # 步骤6：部署到仓库A的gh-pages分支（核心修改）
      - name: Deploy to ForestBlog-Source's gh-pages
        uses: peaceiris/actions-gh-pages@v4  # 简化部署的官方Action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 无需SSH密钥，用仓库自带token
          publish_dir: ./dist  # 部署构建产物目录
          publish_branch: gh-pages  # 部署到仓库A的gh-pages分支
