name: Deploy Astro Site to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 步骤 1: 检出源代码
      - name: Checkout source code
        uses: actions/checkout@v4

      # 步骤 2: 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
          # 先移除 cache 配置，等 pnpm 安装成功后再添加

      # 步骤 3: 通过 corepack 启用 pnpm（Node.js 16+ 内置）
      - name: Enable pnpm with corepack
        run: |
          corepack enable
          corepack prepare pnpm@9.14.4 --activate
          echo "PNPM version: $(pnpm --version)"

      # 步骤 4: 安装项目依赖
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 步骤 5: 构建 Astro 项目
      - name: Build Astro project
        run: pnpm run build

      # 步骤 6: 部署到公开仓库
      - name: Deploy to Public Repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          external_repository: DerckHanna/Pages-Repo
          publish_branch: gh-pages
          publish_dir: ./dist
          force_orphan: true
          keep_files: false

      # 步骤 7: 输出成功信息
      - name: Echo success message
        run: echo "✅ 部署成功！网站已更新。"