name: Deploy Fuwari to Pages-Repo

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ForestBlog-Source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # 关键改进：使用pnpm官方安装脚本，强制安装并获取绝对路径
      - name: Install pnpm with official script
        run: |
          # 下载并执行官方安装脚本
          curl -fsSL https://get.pnpm.io/install.sh | sh -
          
          # 显示pnpm安装路径（通常在~/.local/share/pnpm/pnpm）
          echo "PNPM installation path:"
          which pnpm
          
          # 强制将pnpm路径添加到环境变量
          echo "export PATH=\$HOME/.local/share/pnpm:\$PATH" >> ~/.bashrc
          source ~/.bashrc
          
          # 验证安装是否成功
          echo "pnpm version:"
          pnpm --version || echo "pnpm still not found"
          
          # 记录pnpm的绝对路径（用于后续步骤直接调用）
          echo "PNPM_EXE=$(which pnpm)" >> $GITHUB_ENV

      # 验证环境变量中的pnpm路径
      - name: Verify pnpm path
        run: |
          echo "PNPM_EXE: $PNPM_EXE"
          if [ -z "$PNPM_EXE" ]; then
            echo "Error: PNPM_EXE is not set"
            exit 1
          fi
          if [ ! -f "$PNPM_EXE" ]; then
            echo "Error: pnpm executable not found at $PNPM_EXE"
            exit 1
          fi
          # 确认文件可执行
          chmod +x "$PNPM_EXE"
          "$PNPM_EXE" --version

      # 检查锁文件
      - name: Verify pnpm lock file
        run: |
          if [ ! -f "pnpm-lock.yaml" ]; then
            echo "Error: pnpm-lock.yaml not found. Generate it with 'pnpm install' locally first."
            exit 1
          fi

      # 使用绝对路径安装依赖
      - name: Install dependencies with absolute path
        run: "$PNPM_EXE install"

      # 使用绝对路径构建项目
      - name: Build with absolute path
        run: "$PNPM_EXE run build"

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to Pages-Repo
        run: |
          cd dist
          git init
          git config --global user.name "DerckHanna"
          git config --global user.email "2261629229@qq.com"
          git remote add origin git@github.com:DerckHanna/Pages-Repo.git
          git checkout -b gh-pages
          git add .
          git commit -m "Auto deploy: $(date +'%Y-%m-%d %H:%M:%S')"
          git push -f origin gh-pages
    