name: Deploy Fuwari to Pages-Repo

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ForestBlog-Source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'  # 明确使用pnpm缓存，对应pnpm-lock.yaml

      # 检查pnpm-lock.yaml是否存在（确保依赖锁文件有效）
      - name: Verify pnpm lock file exists
        run: |
          if [ ! -f "pnpm-lock.yaml" ]; then
            echo "Error: pnpm-lock.yaml not found. Please run 'pnpm install' locally to generate it."
            exit 1
          fi

      # 通过npm安装pnpm（确保环境可用）
      - name: Install pnpm via npm
        run: |
          npm install -g pnpm
          pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Build Fuwari site
        run: pnpm run build

      - name: Setup SSH key for Pages-Repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          # VS Code提示"DEPLOY_KEY无效"是正常的（本地无此变量），不影响实际运行
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to Pages-Repo
        run: |
          cd dist
          git init
          git config --global user.name "DerckHanna"
          git config --global user.email "2261629229@qq.com"
          git remote add origin git@github.com:DerckHanna/Pages-Repo.git
          git checkout -b gh-pages
          git add .
          git commit -m "Auto deploy from ForestBlog-Source: $(date +'%Y-%m-%d %H:%M:%S')"
          git push -f origin gh-pages
    